version: 2.1

workflows:
  exercises:
    jobs:
      - python
      - ruby

jobs:
  ruby:
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
      - run: make test-ruby
  python:
    docker:
      - image: python:3.7.3
    steps:
      - checkout
      - run: |
          pip install --no-cache-dir -r python/requirements.txt
          pytest python/**/*_test.py
          ls python/**/*.py | grep -v _test.py | xargs pylint
