version: 2.1

workflows:
  "Python exercises":
    jobs:
      - python
  "Ruby exercises":
    jobs:
      - ruby

jobs:
  ruby:
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
      - run: ls -d ruby/* | xargs -L 1 -I folder bash -c 'cd folder && ruby *_test.rb'
  python:
    docker:
      - image: python:3.7.3
    steps:
      - checkout
      - run: |
          pip install --no-cache-dir -r python/requirements.txt
          pytest python/**/*_test.py
          ls python/**/*.py | grep -v _test.py | xargs pylint
