version: 2.1

workflows:
  exercises:
    jobs:
      - python
      - ruby
      - elixir

jobs:
  ruby:
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
      - run: make test-ruby
  elixir:
    docker:
      - image: elixir:1.9.0
    steps:
      - checkout
      - run: make test-elixir
  python:
    docker:
      - image: python:3.7.3
    steps:
      - checkout
      - run: make test-python
